# Generated by Django 6.0.2 on 2026-02-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bank_account",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMMERCIAL_BANK_OF_ETHIOPIA", "Commercial Bank of Ethiopia"),
                    ("COOPERATIVE_BANK_OF_OROMIA", "Cooperative Bank of Oromia"),
                    ("AWASH_INTERNATIONAL_BANK", "Awash International Bank"),
                    ("BANK_OF_ABYSSINIA", "Bank of Abyssinia"),
                    ("DASHEN_BANK", "Dashen Bank"),
                    ("ENAT_BANK", "Enat Bank"),
                    ("BUNNA_INTERNATIONAL_BANK", "Bunna International Bank"),
                    ("NIB_INTERNATIONAL_BANK", "Nib International Bank"),
                    ("ADDIS_INTERNATIONAL_BANK", "Addis International Bank"),
                    ("AMHARA_BANK", "Amhara Bank"),
                    ("LION_INTERNATIONAL_BANK", "Lion International Bank"),
                    ("DEVELOPMENT_BANK_OF_ETHIOPIA", "Development Bank of Ethiopia"),
                    ("SIDAMA_BANK", "Sidama Bank"),
                    ("SIINQEE_BANK", "Siinqee Bank"),
                    ("TSDEY_BANK", "Tsedey Bank"),
                    ("TSHAY_BANK", "Tsehay Bank"),
                    ("HIBRET_BANK", "Hibret Bank"),
                    ("HIJRA_BANK", "Hijra Bank"),
                    ("RAMMIS_BANK", "Rammis Bank"),
                    ("GADAA_BANK", "Gadaa Bank"),
                    ("NATIONAL_BANK_OF_ETHIOPIA", "National Bank of Ethiopia"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="policy",
            field=models.FileField(blank=True, null=True, upload_to="policy/"),
        ),
    ]
