# Generated by Django 6.0.2 on 2026-02-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_bank_account_user_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
