# Generated by Django 5.1.6 on 2026-02-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_paymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="base_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="followers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="marketer_type",
            field=models.CharField(
                choices=[
                    ("CREATOR", "Content Creator"),
                    ("AGENCY", "Marketing Agency"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("PER_POST", "Per Post"),
                    ("PER_CAMPAIGN", "Per Campaign"),
                    ("MONTHLY", "Monthly Contract"),
                ],
                default="PER_CAMPAIGN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="user",
            name="services",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="team_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tiktok",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="total_jobs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube",
            field=models.URLField(blank=True),
        ),
    ]
