# Generated by Django 5.1.6 on 2026-02-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_user_base_price_user_bio_user_followers_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("SHOP_OWNER", "Shop Owner"),
                    ("SUPPLIER", "Supplier"),
                    ("COURIER", "Courier"),
                    ("MARKETER", "Marketer"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
    ]
