# Generated by Django 5.1.6 on 2026-02-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="services",
            field=models.CharField(blank=True, default="ADS", max_length=255),
        ),
    ]
