# Generated by Django 5.1.6 on 2026-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_user_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="services",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADS", "Paid Ads"),
                    ("CONTENT", "Content Creation"),
                    ("INFLUENCER", "Influencer Promotion"),
                    ("SEO", "SEO Marketing"),
                    ("BRANDING", "Branding"),
                ],
                default="ADS",
                max_length=255,
            ),
        ),
    ]
