# Generated by Django 5.1.6 on 2026-02-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="marketer_commission",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Commission percent for marketer, e.g. 10.00 means 10%",
                max_digits=5,
                null=True,
            ),
        ),
    ]
