# Generated by Django 5.1.6 on 2026-02-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_earning_and_payout_request_updates"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="earning",
            new_name="payment_ear_status_14faf3_idx",
            old_name="payment_earn_status_2f54a9_idx",
        ),
        migrations.RenameIndex(
            model_name="earning",
            new_name="payment_ear_merchan_7eacbf_idx",
            old_name="payment_earn_merchan_615778_idx",
        ),
        migrations.RenameIndex(
            model_name="payoutrequest",
            new_name="payment_pay_status_f300b4_idx",
            old_name="payment_payo_status_7082e4_idx",
        ),
        migrations.RenameIndex(
            model_name="payoutrequest",
            new_name="payment_pay_provide_92bebb_idx",
            old_name="payment_payo_provide_8cc9e6_idx",
        ),
    ]
