# Generated by Django 5.1.6 on 2026-02-25 23:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "catalog",
            "0011_rename_catalog_pro_product_cccc4c_idx_catalog_pro_product_adc547_idx_and_more",
        ),
        ("order", "0002_order_orderitem"),
        ("shop", "0003_fix_legacy_shop_uuid_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketerContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Commission percent, e.g. 10.00 means 10%",
                        max_digits=5,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("ENDED", "Ended"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_marketer_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marketer",
                    models.ForeignKey(
                        limit_choices_to={"role": "MARKETER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketer_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketer_contracts",
                        to="shop.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketerCommission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("APPROVED", "Approved")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketer_commissions",
                        to="order.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketer_commissions",
                        to="order.orderitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketer_commissions",
                        to="catalog.product",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="marketer.marketercontract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketerContractProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_products",
                        to="marketer.marketercontract",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketer_contracts",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="marketercontract",
            index=models.Index(fields=["status"], name="marketer_ma_status_545cc0_idx"),
        ),
        migrations.AddIndex(
            model_name="marketercontract",
            index=models.Index(
                fields=["start_date", "end_date"], name="marketer_ma_start_d_370c35_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketercontract",
            unique_together={("shop", "marketer")},
        ),
        migrations.AddIndex(
            model_name="marketercommission",
            index=models.Index(fields=["status"], name="marketer_ma_status_1dde76_idx"),
        ),
        migrations.AddIndex(
            model_name="marketercommission",
            index=models.Index(
                fields=["contract"], name="marketer_ma_contrac_7a5fad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketercommission",
            index=models.Index(fields=["order"], name="marketer_ma_order_i_54829e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="marketercommission",
            unique_together={("contract", "order_item")},
        ),
        migrations.AddIndex(
            model_name="marketercontractproduct",
            index=models.Index(
                fields=["contract"], name="marketer_ma_contrac_15e883_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketercontractproduct",
            index=models.Index(
                fields=["product"], name="marketer_ma_product_3d7240_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketercontractproduct",
            unique_together={("contract", "product")},
        ),
    ]
