# Generated by Django 5.1.6 on 2026-02-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_fix_legacy_productvariant_uuid_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
