# Generated by Django 5.1.6 on 2026-02-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_productreview"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productreview",
            new_name="catalog_pro_product_adc547_idx",
            old_name="catalog_pro_product_cccc4c_idx",
        ),
        migrations.RenameIndex(
            model_name="productreview",
            new_name="catalog_pro_rating_1c2bd1_idx",
            old_name="catalog_pro_rating_ee403f_idx",
        ),
    ]
