# Generated by Django 5.1.6 on 2026-02-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="shipment",
            new_name="courier_shi_status_61b857_idx",
            old_name="courier_shi_status_03d7de_idx",
        ),
        migrations.RenameIndex(
            model_name="shipment",
            new_name="courier_shi_externa_4dc88b_idx",
            old_name="courier_shi_externa_39e8ea_idx",
        ),
    ]
