# Generated by Django 5.1.6 on 2026-02-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketer", "0001_initial"),
        ("order", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="marketer_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="marketer.marketercontract",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="marketer_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="marketer.marketercontract",
            ),
        ),
    ]
