# Generated by Django 5.1.6 on 2026-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_cartitem_marketer_contract_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[("courier", "Courier"), ("seller", "Seller")],
                default="courier",
                max_length=20,
            ),
        ),
    ]
